### PR TITLE
feat: add insertMenu() and a basic test for it

### PR DESCRIPTION
**Pull request by dlustre**
## Changes

- [x] Create [insertMenu()](https://github.com/icssc/ZotMeal/blob/b1fa25219431512865ac4ac4347ea78acfceb61b/packages/api/src/services/insert.ts#L7) function
- [x] Create basic [test for insertMenu()](https://github.com/icssc/ZotMeal/blob/1d3ec98c9be67683481421e733fd3aaee4891019/packages/api/src/services/insert.test.ts) which makes an insert to the db and then deletes it afterwards
- [x] Modify schemas and parse logic to be able to get rest of the info needed for db
- [x] Add [vitest config](https://github.com/icssc/ZotMeal/blob/b1fa25219431512865ac4ac4347ea78acfceb61b/packages/api/vitest.config.ts)
- [x] Implement [getRestaurant()](https://github.com/icssc/ZotMeal/blob/aaade392733c627d637c54d12e6e236c9c9aaf14/packages/api/src/services/restaurant.ts#L16) function

## Verification?

- [x] Tests pass (**caveat: I had to set maxWorkers = 1 for `turbo test` to work for me locally and for CI to pass**. I believe an alternative would be to increase Node's heap size when running the test, e.g. `NODE_OPTIONS=--max-old-space-size=1536 vitest`. But let me know what we should do)

## Notes

- insertMenu() contains logic to match dishes to their respective stations, maybe it makes more sense to do it in parseMenu()
- (See Verification section)<br>~~`insert.test.ts` only runs & passes for me when I run it individually (`pnpm vitest src/services/insert.test.ts`). I get a memory allocation error when I try doing `turbo test` so idk if we change vitest config or my test is messed up~~

### CODE REVIEW

**Review by bjsilva1 — APPROVED** [review]
Looks good 👍 
Would suggest adding more comments on the code for readibility

**Comment by anmho** [comment]
What was the error that happened when you ran the test before changing the number of workers? My first thought is that theres a race condition/serializing problem since you are creating the Prisma instance outside of the "it" inside describe. Anyways it should not have a major impact on test run time since we have so few.

**Comment by dlustre** [comment]
> What was the error that happened when you ran the test before changing the number of workers?
> 
> My first thought is that theres a race condition/serializing problem since you are creating the Prisma instance outside of the "it" inside describe. Anyways it should not have a major impact on test run time since we have so few.
> 
> nit: Instead of deleting the stuff manually in the test after inserting, you could open a transaction before executing the inserts then roll it back every time.
> 
> Otherwise looks great!

@anmho 

Locally I get a 'memory allocation of 2477428760944 bytes failed' and in CI it's a segfault. It also makes no difference when I moved the prisma instantiation inside of the it

(I gotchu for the rollback 👍)

**Comment by dlustre** [comment]
Note: using a transaction in the test necessitated having to change the db param in every function involved to have the type `PrismaClient | Prisma.TransactionClient` instead because TransactionClient omits some of the properties of PrismaClient. Idk if that's scuffed

**Comment by bjsilva1** [comment]
> Note: using a transaction in the test necessitated having to change the db param in every function involved to have the type `PrismaClient | Prisma.TransactionClient` instead because TransactionClient omits some of the properties of PrismaClient. Idk if that's scuffed

Unless there's a way to cast the `Prisma.TransactionClient` to a `PrismaClient` object to keep the parameter type consistent, I would say keep the manual deletion since we would never run have to rollback actual use case of the function.

**Comment by anmho** [comment]
> Note: using a transaction in the test necessitated having to change the db param in every function involved to have the type `PrismaClient | Prisma.TransactionClient` instead because TransactionClient omits some of the properties of PrismaClient. Idk if that's scuffed

I think changing the db param is a good change actually. If we did a batch insert after scraping campus dish and it failed for some reason we would want to be able to roll everything back cleanly and retry/investigate the problem.

**Pull request merged**
