### PR TITLE
feat: create events scraper and functionality to insert events into db

### PR DESCRIPTION
**Pull request by dlustre**
## Describe your changes

Create functions to scrape events data with cheerio and batch insert the events data to db.

## Change Checklist

- [x] Create [scrapeEvents()](https://github.com/icssc/ZotMeal/blob/e5b16eb9c13d91bbcd10e042735a00788bcb9d69/packages/api/src/services/event.ts#L20) which formats & validates scraped data into [EventSchema](https://github.com/icssc/ZotMeal/blob/e5b16eb9c13d91bbcd10e042735a00788bcb9d69/packages/validators/src/zotmeal.ts#L86)
- [x] Create [insertEvents()](https://github.com/icssc/ZotMeal/blob/e5b16eb9c13d91bbcd10e042735a00788bcb9d69/packages/api/src/services/event.ts#L77) which takes in an array of events and performs a batch insert. **The caller decides whether to perform the batch insert as a transaction.**

## Verification?

- [x] Tests pass

## Notes

- Currently, events are not matched to a restaurant - it's possible, but it would require having to perform another fetch + scrape within each event item because the restaurant info is only available in the event's own page, not in the api response
- I defined the Event prisma model to have a composite key of [title, link, date]. e.g. Since the event below takes place in both anteatery and brandywine, the db will create two separate Event records because the links are different. So we're pretty much doing the same as campusdish right now but let me know if we're interested in deduplicating events like this

image

### CODE REVIEW

**Review by anmho — COMMENTED** [review]
For your tests, instead of catching the error and seeing the erroroccurred flag, you could wrap it in a 
`expect(()=>{}.not.toThrow(SomeKindOfError)`

**Comment by anmho** [comment]
What are some options for matching events to restaurant? Is there a hidden query param for location possibly?

**Comment by dlustre** [comment]
> What are some options for matching events to restaurant? Is there a hidden query param for location possibly?

@anmho 

[Brandywine's page](https://uci.campusdish.com/LocationsAndMenus/Brandywine) displays Brandywine-specific events. Maybe we can just filter out the events with just that. Anteatery page doesn't have events shown

**Review by anmho — APPROVED** [review]
lgtm!

**Pull request merged**
