### PR TITLE
refactor: pnpm-workspaces based setup

### PR DESCRIPTION
**Pull request by ap0nia**
# Summary
Reworked the project structure to use `pnpm-workspaces` as the foundation.

## Details
- Removed the symlinks because I don't like them
- Removed a lot of the root configuration files because those should be local to projects
- The new app is in `apps/zotmeal`
- Preserved the majority of the legacy stuff in the `apps`

## App Details
- Uses [NativeWind](https://www.nativewind.dev/), i.e. TailwindCSS for React-Native
- Uses expo router and `src/app` directory
  https://docs.expo.dev/routing/introduction/
  https://docs.expo.dev/router/reference/src-directory/
- Uses shared packages, e.g. the `ui` package at `packages/ui`
   Babel doesn't actually transpile anything from workspace packages for some reason.
   This is typical behavior tbh; you're expected to build the package's outputs and import those.
   But Vite's able to import and transpile on the fly just fine :shrug: 
- Works on my laptop and my iPhone

### CODE REVIEW

**Review by dlustre — APPROVED** [review]
Works on my Windows, iOS, and Android.

**Review by bjsilva1 — COMMENTED** [review]
running locally works on web, ios, and android
you can go ahead and start migrating the UI components over to the new expo app 👍

**Review by KatyH820 — APPROVED** [review]
This work on web, ios, and android! We can start migrating our ui now :D! TYSM

**Comment by KatyH820** [comment]
> Would you guys like to do some more work on this branch? Or do you want to merge it in and just append adjustments via new branches and PRs to main?

I think we can go ahead and merge it in and append other adjustments through new branches. But I would like to hear Bryan's opinions as well.

**Comment by KatyH820** [comment]
I just linked the netlify here as well.

**Pull request merged**
